/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 color scheme (matches stitchFile design system)
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'secondary-container': '#d0e1fb',
        'tertiary-fixed-dim': '#c3c7cb',
        'on-secondary-fixed': '#0b1c30',
        'tertiary-fixed': '#dfe3e7',
        'primary-container': '#2170e4',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#b7c8e1',
        'surface-bright': '#faf8ff',
        'on-primary-fixed-variant': '#004395',
        'primary-fixed': '#d8e2ff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e2e7ff',
        'on-primary-container': '#fefcff',
        'on-secondary-fixed-variant': '#38485d',
        'secondary-fixed': '#d3e4fe',
        error: '#ba1a1a',
        surface: '#faf8ff',
        'on-primary-fixed': '#001a42',
        'surface-tint': '#005ac2',
        'surface-container-low': '#f2f3ff',
        'inverse-surface': '#283044',
        'on-tertiary': '#ffffff',
        'surface-dim': '#d2d9f4',
        'on-tertiary-fixed-variant': '#43474b',
        background: '#faf8ff',
        tertiary: '#585d60',
        'surface-container': '#eaedff',
        'inverse-on-surface': '#eef0ff',
        'on-tertiary-container': '#fbfcff',
        'on-tertiary-fixed': '#171c1f',
        'on-primary': '#ffffff',
        secondary: '#505f76',
        'inverse-primary': '#adc6ff',
        primary: '#0058be',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#adc6ff',
        outline: '#727785',
        'on-secondary-container': '#54647a',
        'on-surface-variant': '#424754',
        'tertiary-container': '#707579',
        'surface-variant': '#dae2fd',
        'on-background': '#131b2e',
        'outline-variant': '#c2c6d6',
        // Status colors
        success: { 500: '#22c55e', 600: '#16a34a' },
        warning: { 500: '#f59e0b', 600: '#d97706' },
        danger: { 500: '#ef4444', 600: '#dc2626' },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '1rem',
        gutter: '1.5rem',
        'unit-sm': '0.5rem',
        'container-max': '1280px',
        'margin-desktop': '2.5rem',
        'unit-xs': '0.25rem',
        'unit-md': '1rem',
        'unit-lg': '2rem',
      },
      fontFamily: {
        arabic: ['IBM Plex Sans Arabic', 'sans-serif'],
        'body-md': ['IBM Plex Sans Arabic', 'sans-serif'],
        'body-lg': ['IBM Plex Sans Arabic', 'sans-serif'],
        'headline-md': ['IBM Plex Sans Arabic', 'sans-serif'],
        'display-lg': ['IBM Plex Sans Arabic', 'sans-serif'],
        'headline-lg': ['IBM Plex Sans Arabic', 'sans-serif'],
        caption: ['IBM Plex Sans Arabic', 'sans-serif'],
        'label-md': ['IBM Plex Sans Arabic', 'sans-serif'],
        'title-lg': ['IBM Plex Sans Arabic', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['40px', { lineHeight: '52px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
      boxShadow: {
        card: '0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -1px rgba(0,0,0,0.03)',
        modal: '0 20px 60px -10px rgba(0,0,0,0.15)',
      },
    },
  },
  plugins: [],
};
